version: "3.3"

services:
  db:
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_DATABASE=recipe-db
      - MYSQL_ROOT_PASSWORD=${MY_SQL_ROOT_PASSWORD}
    volumes:
      - recipe-db:/var/lib/mysql
    ports:
      - "3306:3306"

  minio:
    image: minio/minio
    command: minio server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${SECRET_ACCESS_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "${BUCKET_DOMAIN}/minio/health/live"]
      interval: 15s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      - reci-one

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${ACCESS_KEY_ID} ${SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/${BUCKET_NAME};
      "
    networks:
      - reci-one

volumes:
  recipe-db:
  minio-data:

networks:
  reci-one:
