version: "3.3"

services:
  next:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    networks:
      - reci-one
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_DATABASE=${MY_SQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MY_SQL_ROOT_PASSWORD}
    volumes:
      - reci-one-db:/var/lib/mysql
    networks:
      - reci-one
    ports:
      - "3306:3306"

  parser:
    build: ./parser
    environment:
      FLASK_DEBUG: TRUE
    ports:
      - "8000:8000"
    volumes:
      - ./parser:/parser
    networks:
      - reci-one

  minio:
    image: minio/minio
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${SECRET_ACCESS_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "${BUCKET_DOMAIN}/minio/health/live"]
      interval: 15s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      - reci-one

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${ACCESS_KEY_ID} ${SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/${BUCKET_NAME};
      "
    networks:
      - reci-one

volumes:
  reci-one-db:
  minio-data:

networks:
  reci-one:
