name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

env:
  MY_SQL_ROOT_PASSWORD: ${{secret.MY_SQL_ROOT_PASSWORD}}
  DATABASE_URL: ${{secret.NEXTAUTH_SECRET}}
  NEXTAUTH_SECRET: ${{secret.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{secret.NEXTAUTH_URL}}
  PATH_TO_KEYFILE: ${{secret.PATH_TO_KEYFILE}}
  BUCKET_NAME: ${{secret.BUCKET_NAME}}
  GITHUB_CLIENT_ID: ${{secret.NEXTAUTH_GITHUB_CLIENT_ID}}
  GITHUB_CLIENT_SECRET: ${{secret.NEXTAUTH_GITHUB_CLIENT_SECRET}

jobs:
  format_and_lint:
    name: Check Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm install

      - name: Prettier
        run: npm run format:check

      - name: Lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm install

      - name: Build Nextjs App
        run: npm run build
