name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm install

      - name: Prettier
        run: npm run format:check

      - name: Lint
        run: npm run lint

  # Removed b/c vercel has auto build
  # Note: env variables aren't configured here yet
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.13.x
  #         cache: npm

  #     - name: Install
  #       run: npm install

  #     - name: Build Nextjs App
  #       run: npm run build
